#!/usr/bin/env bash
BLOG_DATE=$(date "+%Y-%m-%d")
BLOG_NAME=$*
cat > "./_posts/${BLOG_DATE}-$BLOG_NAME.md" <<EOF
---
layout: post
title: $BLOG_NAME
date: $BLOG_DATE
typora-root-url: ../
catalog: true
tags:
  - 这是一个占位符
---
EOF
